// Flat ESLint config. Three code environments live in this repo:
//   • the browser flight shell + engine core — ES modules that read a few
//     ambient globals injected by the build (DATA/MANIFEST/NAMES/EV);
//   • the Node toolchain (evexport, tmpl2schema, loader/verify) — CommonJS;
//   • the in-browser loader — dual-use libraries (evrsrc/semantics/decoders run
//     in both Node and the browser) and the worker entry (launch/sw), which
//     talk to each other through a handful of script-scope globals.
// Correctness-focused for now (no stylistic/formatting rules).
const js = require('@eslint/js');
const globals = require('globals');

const shellGlobals = {
  ...globals.browser,
  // injected into the flight template <script> before the shell bundle runs
  DATA: 'readonly',
  MANIFEST: 'readonly',
  NAMES: 'readonly',
  EV: 'readonly',
};

// The loader's scripts (evrsrc/semantics/decoders/launch) publish onto the
// worker's global scope for their siblings to pick up; each is also require()d
// in Node. Treat those cross-script names as ambient readonly globals.
const loaderGlobals = {
  EVRSRC: 'readonly',
  SEMANTICS: 'readonly',
  EVBUILD: 'readonly',
  decodePict: 'readonly',
  decodeSnd: 'readonly',
  compositeSprite: 'readonly',
  parseSit: 'readonly',
  extractFork: 'readonly',
  unstuff13: 'readonly',
  toFloat32: 'readonly',
  VELAUNCH: 'writable',
  Buffer: 'readonly',
};

const correctness = {
  'prefer-const': 'error',
  'no-var': 'error',
  eqeqeq: ['error', 'smart'],
  'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
  'no-empty': ['error', { allowEmptyCatch: true }],
};

module.exports = [
  {
    ignores: [
      'node_modules/**',
      'engine/*.bundle.js', // generated by esbuild
      'flight.html',
      'galaxy.html',
      'evdata.json',
      'evassets/**',
      'EV_data/**',
      'schemas/**',
    ],
  },
  js.configs.recommended,

  // Browser flight shell + DOM-free engine core (ES modules)
  {
    files: ['engine/core.js', 'engine/shell/**/*.js'],
    languageOptions: { ecmaVersion: 'latest', sourceType: 'module', globals: shellGlobals },
    rules: correctness,
  },

  // Node CommonJS tools
  {
    files: [
      'evexport.js',
      'evatlas.js',
      'evpilot.js',
      'tmpl2schema.js',
      'eslint.config.js',
      'loader/verify.js',
    ],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'commonjs',
      globals: { ...globals.node },
    },
    rules: correctness,
  },

  // Dual-use libraries: require/module.exports in Node, published as globals in
  // the browser loader.
  {
    files: [
      'evrsrc.js',
      'pilot-codec.js',
      'semantics.js',
      'loader/evbuild.js',
      'loader/evpict.js',
      'loader/evsit.js',
      'loader/evsnd.js',
      'loader/evsprite.js',
      'loader/nodeshim.js',
    ],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'commonjs',
      globals: { ...globals.node, ...globals.browser, ...loaderGlobals },
    },
    rules: correctness,
  },

  // Node test suite (node:test / node:assert, ES modules)
  {
    files: ['test/**/*.mjs'],
    languageOptions: { ecmaVersion: 'latest', sourceType: 'module', globals: { ...globals.node } },
    rules: correctness,
  },

  // In-browser loader entry + service worker
  {
    files: ['loader/launch.js', 'loader/sw.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: { ...globals.browser, ...globals.serviceworker, ...loaderGlobals },
    },
    rules: correctness,
  },
];
